version: '3'

services:

  postgres-db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - $GOPATH/src/github.com/SaenkoDmitry/advertisement-app/db/data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - back
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        db_host: host.docker.internal
    restart: on-failure
    networks:
      - back
    depends_on:
      - postgres-db
    ports:
      - 8080:8080

networks:
  back:
    driver: bridge
